### ISSUE TITLE
vew: Enable forwarding_path enforcement

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-sp-infrabstract#160]
Forwarding path setup inside the emulator using  the corresponding network/ endpoints of the REST API.

**Comment by mpeuster** [comment]
Implement VimEmuNetwork wrapper, like: https://github.com/sonata-nfv/son-sp-infrabstract/blob/master/vim-adaptor/adaptor/src/main/java/sonata/kernel/vimadaptor/wrapper/ovsWrapper/OvsWrapper.java

Use VNFRs to get interface names of containers (might require extension of vim-emu compute start API, to be checked)

**Comment by frederictobiasc** [comment]
Track: VduRecord.vduReference

**Comment by frederictobiasc** [comment]
Todos:
- [ ] Assemble and send NetworkConfigurePayload on Messagebroker (VIMEmuIntegrationTest)
- [ ] Translate NetworkConfigurePayload into API calls on vim-emu
- [ ] Answer?

**Comment by frederictobiasc** [comment]
Relevant topics according to AdaptorDispatcher are:
- `infrastructure.service.chain.configure`
- `infrastructure.service.chain.deconfigure`

**Comment by frederictobiasc** [comment]
Is instance_uuid really defined in vnfd? Ex:
https://github.com/sonata-nfv/son-sp-infrabstract/blob/a310720add5eb96d8434d122797ce0931bf8ad14/wim-adaptor/adaptor/YAML/firewall-vnfd.yml#L54

**Comment by frederictobiasc** [comment]
- [ ] fix failed repo writing due to missing instance_uuid https://github.com/frederictobiasc/son-sp-infrabstract/blob/82cba693f3adfd4ed99d1fa37d88a9791b723a96/vim-adaptor/adaptor/src/main/java/sonata/kernel/vimadaptor/wrapper/vimemu/VIMEmuComputeWrapper.java#L155

**Comment by mpeuster** [comment]
- [ ] test connectivity between deployed containers
    - [ ] ICMP (ping)
    - [ ] TCP (http)
