### ISSUE TITLE
vew: Document basic usage of vim-emu-wrapper

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-sp-infrabstract#161]
How to install?
How to configure build env? 
How to execute tests?

**Comment by frederictobiasc** [comment]
[First version](https://github.com/frederictobiasc/son-sp-infrabstract/blob/9fcdebf4bcd36aa262f7e14340bc06840ed0d470/vim-adaptor/standalone.md)
[] Add necessary configuration files
[] Decision: Placement of VIMEmuIntegrationTest (test-classes are not included in JAR)
[] Document maven workflow
[] Clean test

**Comment by frederictobiasc** [comment]
Now at [wiki](https://github.com/sonata-nfv/son-sp-infrabstract/wiki/Standalone-setup-and-testing)
- [ ] Review

**Comment by mpeuster** [comment]
Looks good to me.
