### ISSUE TITLE
vew: Setup a dedicated demo/sandbox VM with full SONATA SP and emulator to showcase VEW

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-sp-infrabstract#168]
The foreseen steps as discussed on 2018-05-09:

- [x] install full SONATA SP in VM (user version 3.1)
- [x] replace standard IA with our patched IA that includes VEW code
- [x] install emulator on VM
- [x] deploy a first test service end-to-end
    - [x] create a service package
    - [x] on-board service package
    - [x] instantiate the test service
    - [x] check test service deployed in emulator (ping, http, etc.)
- [x] build a shiny demo service for demonstrations

**Comment by mpeuster** [comment]
@frederictobiasc test 123

**Comment by frederictobiasc** [comment]
No add vim available: 
![no vim](https://user-images.githubusercontent.com/26125115/40829453-c4d36c78-6583-11e8-8c64-c2e176d73a90.png)

**Comment by mpeuster** [comment]
https://gist.github.com/mpeuster/65592a00032730bdb893482f07950f5f

**Comment by frederictobiasc** [comment]
vm ready
