### ISSUE TITLE
Adding a VIM with a custom Keystone Port

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-sp-infrabstract#83]
Hi,

The IA now supports the Keystone API to fetch all the other endpoints. This works well.

But, it is not possible to specify the port of the Keystone API to use. This one is hardcoded :-(

Couldn't we have a field in the `infrastructure.management.compute.add` that supports the specification of the `vim_port` in addition to `vim_address`? This would really make the IA much more flexible.

**Comment by DarioValocchi** [comment]
Since this information is VIM specific, we can add it without problems. It could be left empty if default port is used.

**Comment by mpeuster** [comment]
Exactly. Just add an optional property. 👍

**Comment by DarioValocchi** [comment]
Feature developed. One can specify an `identity_port:String` parameter in the `configuration:{...}` object of the payload of the `infrastructure.management.compute.add` API. The value is actually used only when adding an OpenStack Wrapper. The port is used to connect to the VIM Identity service.
In Progress, part of PR #84. Currently under test.

**Comment by DarioValocchi** [comment]
PR #84 merged. @mpeuster you can checkout the code and try the feature.

**Comment by mpeuster** [comment]
Thanks for your effort. But there seems still to be a small bug.

I use the following payload for ``:

```json
{"vim_type":"Heat", "configuration":{"tenant_ext_router":"26f732b2-74bd-4f8c-a60e-dae4fb6a7c14", "tenant_ext_net":"53d43a3e-8c86-48e6-b1cb-f1f2c48833de","tenant":"tenantName","identity_port":"6001"},"city":"Paderborn","country":"Germany","vim_address":"127.0.0.1","username":"username","name":"EmulatorVim1","pass":"password"}
```

But in https://github.com/sonata-nfv/son-sp-infrabstract/blob/master/vim-adaptor/adaptor/src/main/java/sonata/kernel/vimadaptor/wrapper/openstack/javastackclient/JavaStackCore.java#L229 `customIdentityPort ` stays `null` and the default port is used.

I was not yet able to track this further down.

**Comment by DarioValocchi** [comment]
Thank @mpeuster for the report. I couldn't test it extensively since I don't have a custom VIM with a custom port to use. I will look into it.

**Comment by mpeuster** [comment]
Good morning. I tested the fix and I can confirm that the custom port feature works now. Thanks again for adding this.
